name: Publish NuGet

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    environment: nuget
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        run: dotnet pack src/Rom.Annotations/Rom.Annotations.csproj --configuration Release --no-build -o ./nupkg
      
      - name: List nupkg files
        run: dir ./nupkg
      
      - name: Publish to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
